//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KangoMetody.ServiceKango {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSProjekt", Namespace="http://schemas.datacontract.org/2004/07/KmenWS")]
    [System.SerializableAttribute()]
    public partial class WSProjekt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime platnyDoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime platnyOdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string poznamkaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iD {
            get {
                return this.iDField;
            }
            set {
                if ((this.iDField.Equals(value) != true)) {
                    this.iDField = value;
                    this.RaisePropertyChanged("iD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nazov {
            get {
                return this.nazovField;
            }
            set {
                if ((object.ReferenceEquals(this.nazovField, value) != true)) {
                    this.nazovField = value;
                    this.RaisePropertyChanged("nazov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime platnyDo {
            get {
                return this.platnyDoField;
            }
            set {
                if ((this.platnyDoField.Equals(value) != true)) {
                    this.platnyDoField = value;
                    this.RaisePropertyChanged("platnyDo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime platnyOd {
            get {
                return this.platnyOdField;
            }
            set {
                if ((this.platnyOdField.Equals(value) != true)) {
                    this.platnyOdField = value;
                    this.RaisePropertyChanged("platnyOd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string poznamka {
            get {
                return this.poznamkaField;
            }
            set {
                if ((object.ReferenceEquals(this.poznamkaField, value) != true)) {
                    this.poznamkaField = value;
                    this.RaisePropertyChanged("poznamka");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSEntityInfo", Namespace="http://schemas.datacontract.org/2004/07/KmenWS")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KangoMetody.ServiceKango.WSEntity))]
    public partial class WSEntityInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool enabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSPropertyInfo[] propertyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSVerzia versionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool enabled {
            get {
                return this.enabledField;
            }
            set {
                if ((this.enabledField.Equals(value) != true)) {
                    this.enabledField = value;
                    this.RaisePropertyChanged("enabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iD {
            get {
                return this.iDField;
            }
            set {
                if ((this.iDField.Equals(value) != true)) {
                    this.iDField = value;
                    this.RaisePropertyChanged("iD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSPropertyInfo[] property {
            get {
                return this.propertyField;
            }
            set {
                if ((object.ReferenceEquals(this.propertyField, value) != true)) {
                    this.propertyField = value;
                    this.RaisePropertyChanged("property");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSVerzia version {
            get {
                return this.versionField;
            }
            set {
                if ((object.ReferenceEquals(this.versionField, value) != true)) {
                    this.versionField = value;
                    this.RaisePropertyChanged("version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSVerzia", Namespace="http://schemas.datacontract.org/2004/07/KmenWS")]
    [System.SerializableAttribute()]
    public partial class WSVerzia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] updatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime validFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string versionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] updates {
            get {
                return this.updatesField;
            }
            set {
                if ((object.ReferenceEquals(this.updatesField, value) != true)) {
                    this.updatesField = value;
                    this.RaisePropertyChanged("updates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime validFrom {
            get {
                return this.validFromField;
            }
            set {
                if ((this.validFromField.Equals(value) != true)) {
                    this.validFromField = value;
                    this.RaisePropertyChanged("validFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                if ((object.ReferenceEquals(this.versionField, value) != true)) {
                    this.versionField = value;
                    this.RaisePropertyChanged("version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSEntity", Namespace="http://schemas.datacontract.org/2004/07/KmenWS")]
    [System.SerializableAttribute()]
    public partial class WSEntity : KangoMetody.ServiceKango.WSEntityInfo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] dataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSPropertyInfo", Namespace="http://schemas.datacontract.org/2004/07/KmenWS")]
    [System.SerializableAttribute()]
    public partial class WSPropertyInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool enabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int indexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int lengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool enabled {
            get {
                return this.enabledField;
            }
            set {
                if ((this.enabledField.Equals(value) != true)) {
                    this.enabledField = value;
                    this.RaisePropertyChanged("enabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int index {
            get {
                return this.indexField;
            }
            set {
                if ((this.indexField.Equals(value) != true)) {
                    this.indexField = value;
                    this.RaisePropertyChanged("index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int length {
            get {
                return this.lengthField;
            }
            set {
                if ((this.lengthField.Equals(value) != true)) {
                    this.lengthField = value;
                    this.RaisePropertyChanged("length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSData", Namespace="http://schemas.datacontract.org/2004/07/KmenWS")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ushort[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(int[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KangoMetody.ServiceKango.WSProjekt[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KangoMetody.ServiceKango.WSProjekt))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KangoMetody.ServiceKango.WSEntityInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KangoMetody.ServiceKango.WSEntityInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KangoMetody.ServiceKango.WSPropertyInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KangoMetody.ServiceKango.WSPropertyInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KangoMetody.ServiceKango.WSFid))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KangoMetody.ServiceKango.WSFid[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KangoMetody.ServiceKango.WSVerzia))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KangoMetody.ServiceKango.WSData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KangoMetody.ServiceKango.WSEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KangoMetody.ServiceKango.WSInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KangoMetody.ServiceKango.WSMethodInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KangoMetody.ServiceKango.WSMethodInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KangoMetody.ServiceKango.WSDataTTP[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KangoMetody.ServiceKango.WSDataTTP))]
    public partial class WSData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] valuesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] values {
            get {
                return this.valuesField;
            }
            set {
                if ((object.ReferenceEquals(this.valuesField, value) != true)) {
                    this.valuesField = value;
                    this.RaisePropertyChanged("values");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSFid", Namespace="http://schemas.datacontract.org/2004/07/KmenWS")]
    [System.SerializableAttribute()]
    public partial class WSFid : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int entityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] fkeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int entityID {
            get {
                return this.entityIDField;
            }
            set {
                if ((this.entityIDField.Equals(value) != true)) {
                    this.entityIDField = value;
                    this.RaisePropertyChanged("entityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] fkey {
            get {
                return this.fkeyField;
            }
            set {
                if ((object.ReferenceEquals(this.fkeyField, value) != true)) {
                    this.fkeyField = value;
                    this.RaisePropertyChanged("fkey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSInfo", Namespace="http://schemas.datacontract.org/2004/07/KmenWS")]
    [System.SerializableAttribute()]
    public partial class WSInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSMethodInfo[] methodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSVerzia versionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSMethodInfo[] method {
            get {
                return this.methodField;
            }
            set {
                if ((object.ReferenceEquals(this.methodField, value) != true)) {
                    this.methodField = value;
                    this.RaisePropertyChanged("method");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSVerzia version {
            get {
                return this.versionField;
            }
            set {
                if ((object.ReferenceEquals(this.versionField, value) != true)) {
                    this.versionField = value;
                    this.RaisePropertyChanged("version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSMethodInfo", Namespace="http://schemas.datacontract.org/2004/07/KmenWS")]
    [System.SerializableAttribute()]
    public partial class WSMethodInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] parameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prototypField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string retvalueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] parameter {
            get {
                return this.parameterField;
            }
            set {
                if ((object.ReferenceEquals(this.parameterField, value) != true)) {
                    this.parameterField = value;
                    this.RaisePropertyChanged("parameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prototyp {
            get {
                return this.prototypField;
            }
            set {
                if ((object.ReferenceEquals(this.prototypField, value) != true)) {
                    this.prototypField = value;
                    this.RaisePropertyChanged("prototyp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string retvalue {
            get {
                return this.retvalueField;
            }
            set {
                if ((object.ReferenceEquals(this.retvalueField, value) != true)) {
                    this.retvalueField = value;
                    this.RaisePropertyChanged("retvalue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSDataTTP", Namespace="http://schemas.datacontract.org/2004/07/KmenWS")]
    [System.SerializableAttribute()]
    public partial class WSDataTTP : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab10DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData tab10ZahlavieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab11DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData tab11ZahlavieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab12DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData tab12ZahlavieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab13DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData tab13ZahlavieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab1DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab1DispPracoviskoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab1RadiovySystemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab1TrakcnaSustavaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData tab1ZahlavieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab2DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData tab2ZahlavieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab3aDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData tab3aZahlavieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab3bDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData tab3bZahlavieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab4DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab4TratETCSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData tab4ZahlavieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab5DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData tab5ZahlavieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab6aDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab6aUsekTrateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab6aZabrzdnaVzdialenostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData tab6aZahlavieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab6b0DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab6b0UsekTrateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab6b0ZabrzdnaVzdialenostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData tab6b0ZahlavieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab6b1DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab6b1UsekTrateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab6b1ZabrzdnaVzdialenostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData tab6b1ZahlavieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab6b2DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab6b2UsekTrateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab6b2ZabrzdnaVzdialenostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData tab6b2ZahlavieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab6b3DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab6b3UsekTrateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab6b3ZabrzdnaVzdialenostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData tab6b3ZahlavieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab6b4DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab6b4UsekTrateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab6b4ZabrzdnaVzdialenostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData tab6b4ZahlavieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab6b5DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab6b5UsekTrateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab6b5ZabrzdnaVzdialenostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData tab6b5ZahlavieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab7DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData tab7ZahlavieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab8aDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab8aRekuperaciaDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData tab8aRekuperaciaZahlavieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData tab8aZahlavieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab8bDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData tab8bZahlavieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData[] tab9DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KangoMetody.ServiceKango.WSData tab9ZahlavieField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab10Data {
            get {
                return this.tab10DataField;
            }
            set {
                if ((object.ReferenceEquals(this.tab10DataField, value) != true)) {
                    this.tab10DataField = value;
                    this.RaisePropertyChanged("tab10Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData tab10Zahlavie {
            get {
                return this.tab10ZahlavieField;
            }
            set {
                if ((object.ReferenceEquals(this.tab10ZahlavieField, value) != true)) {
                    this.tab10ZahlavieField = value;
                    this.RaisePropertyChanged("tab10Zahlavie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab11Data {
            get {
                return this.tab11DataField;
            }
            set {
                if ((object.ReferenceEquals(this.tab11DataField, value) != true)) {
                    this.tab11DataField = value;
                    this.RaisePropertyChanged("tab11Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData tab11Zahlavie {
            get {
                return this.tab11ZahlavieField;
            }
            set {
                if ((object.ReferenceEquals(this.tab11ZahlavieField, value) != true)) {
                    this.tab11ZahlavieField = value;
                    this.RaisePropertyChanged("tab11Zahlavie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab12Data {
            get {
                return this.tab12DataField;
            }
            set {
                if ((object.ReferenceEquals(this.tab12DataField, value) != true)) {
                    this.tab12DataField = value;
                    this.RaisePropertyChanged("tab12Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData tab12Zahlavie {
            get {
                return this.tab12ZahlavieField;
            }
            set {
                if ((object.ReferenceEquals(this.tab12ZahlavieField, value) != true)) {
                    this.tab12ZahlavieField = value;
                    this.RaisePropertyChanged("tab12Zahlavie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab13Data {
            get {
                return this.tab13DataField;
            }
            set {
                if ((object.ReferenceEquals(this.tab13DataField, value) != true)) {
                    this.tab13DataField = value;
                    this.RaisePropertyChanged("tab13Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData tab13Zahlavie {
            get {
                return this.tab13ZahlavieField;
            }
            set {
                if ((object.ReferenceEquals(this.tab13ZahlavieField, value) != true)) {
                    this.tab13ZahlavieField = value;
                    this.RaisePropertyChanged("tab13Zahlavie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab1Data {
            get {
                return this.tab1DataField;
            }
            set {
                if ((object.ReferenceEquals(this.tab1DataField, value) != true)) {
                    this.tab1DataField = value;
                    this.RaisePropertyChanged("tab1Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab1DispPracovisko {
            get {
                return this.tab1DispPracoviskoField;
            }
            set {
                if ((object.ReferenceEquals(this.tab1DispPracoviskoField, value) != true)) {
                    this.tab1DispPracoviskoField = value;
                    this.RaisePropertyChanged("tab1DispPracovisko");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab1RadiovySystem {
            get {
                return this.tab1RadiovySystemField;
            }
            set {
                if ((object.ReferenceEquals(this.tab1RadiovySystemField, value) != true)) {
                    this.tab1RadiovySystemField = value;
                    this.RaisePropertyChanged("tab1RadiovySystem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab1TrakcnaSustava {
            get {
                return this.tab1TrakcnaSustavaField;
            }
            set {
                if ((object.ReferenceEquals(this.tab1TrakcnaSustavaField, value) != true)) {
                    this.tab1TrakcnaSustavaField = value;
                    this.RaisePropertyChanged("tab1TrakcnaSustava");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData tab1Zahlavie {
            get {
                return this.tab1ZahlavieField;
            }
            set {
                if ((object.ReferenceEquals(this.tab1ZahlavieField, value) != true)) {
                    this.tab1ZahlavieField = value;
                    this.RaisePropertyChanged("tab1Zahlavie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab2Data {
            get {
                return this.tab2DataField;
            }
            set {
                if ((object.ReferenceEquals(this.tab2DataField, value) != true)) {
                    this.tab2DataField = value;
                    this.RaisePropertyChanged("tab2Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData tab2Zahlavie {
            get {
                return this.tab2ZahlavieField;
            }
            set {
                if ((object.ReferenceEquals(this.tab2ZahlavieField, value) != true)) {
                    this.tab2ZahlavieField = value;
                    this.RaisePropertyChanged("tab2Zahlavie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab3aData {
            get {
                return this.tab3aDataField;
            }
            set {
                if ((object.ReferenceEquals(this.tab3aDataField, value) != true)) {
                    this.tab3aDataField = value;
                    this.RaisePropertyChanged("tab3aData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData tab3aZahlavie {
            get {
                return this.tab3aZahlavieField;
            }
            set {
                if ((object.ReferenceEquals(this.tab3aZahlavieField, value) != true)) {
                    this.tab3aZahlavieField = value;
                    this.RaisePropertyChanged("tab3aZahlavie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab3bData {
            get {
                return this.tab3bDataField;
            }
            set {
                if ((object.ReferenceEquals(this.tab3bDataField, value) != true)) {
                    this.tab3bDataField = value;
                    this.RaisePropertyChanged("tab3bData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData tab3bZahlavie {
            get {
                return this.tab3bZahlavieField;
            }
            set {
                if ((object.ReferenceEquals(this.tab3bZahlavieField, value) != true)) {
                    this.tab3bZahlavieField = value;
                    this.RaisePropertyChanged("tab3bZahlavie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab4Data {
            get {
                return this.tab4DataField;
            }
            set {
                if ((object.ReferenceEquals(this.tab4DataField, value) != true)) {
                    this.tab4DataField = value;
                    this.RaisePropertyChanged("tab4Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab4TratETCS {
            get {
                return this.tab4TratETCSField;
            }
            set {
                if ((object.ReferenceEquals(this.tab4TratETCSField, value) != true)) {
                    this.tab4TratETCSField = value;
                    this.RaisePropertyChanged("tab4TratETCS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData tab4Zahlavie {
            get {
                return this.tab4ZahlavieField;
            }
            set {
                if ((object.ReferenceEquals(this.tab4ZahlavieField, value) != true)) {
                    this.tab4ZahlavieField = value;
                    this.RaisePropertyChanged("tab4Zahlavie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab5Data {
            get {
                return this.tab5DataField;
            }
            set {
                if ((object.ReferenceEquals(this.tab5DataField, value) != true)) {
                    this.tab5DataField = value;
                    this.RaisePropertyChanged("tab5Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData tab5Zahlavie {
            get {
                return this.tab5ZahlavieField;
            }
            set {
                if ((object.ReferenceEquals(this.tab5ZahlavieField, value) != true)) {
                    this.tab5ZahlavieField = value;
                    this.RaisePropertyChanged("tab5Zahlavie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab6aData {
            get {
                return this.tab6aDataField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6aDataField, value) != true)) {
                    this.tab6aDataField = value;
                    this.RaisePropertyChanged("tab6aData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab6aUsekTrate {
            get {
                return this.tab6aUsekTrateField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6aUsekTrateField, value) != true)) {
                    this.tab6aUsekTrateField = value;
                    this.RaisePropertyChanged("tab6aUsekTrate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab6aZabrzdnaVzdialenost {
            get {
                return this.tab6aZabrzdnaVzdialenostField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6aZabrzdnaVzdialenostField, value) != true)) {
                    this.tab6aZabrzdnaVzdialenostField = value;
                    this.RaisePropertyChanged("tab6aZabrzdnaVzdialenost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData tab6aZahlavie {
            get {
                return this.tab6aZahlavieField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6aZahlavieField, value) != true)) {
                    this.tab6aZahlavieField = value;
                    this.RaisePropertyChanged("tab6aZahlavie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab6b0Data {
            get {
                return this.tab6b0DataField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6b0DataField, value) != true)) {
                    this.tab6b0DataField = value;
                    this.RaisePropertyChanged("tab6b0Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab6b0UsekTrate {
            get {
                return this.tab6b0UsekTrateField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6b0UsekTrateField, value) != true)) {
                    this.tab6b0UsekTrateField = value;
                    this.RaisePropertyChanged("tab6b0UsekTrate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab6b0ZabrzdnaVzdialenost {
            get {
                return this.tab6b0ZabrzdnaVzdialenostField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6b0ZabrzdnaVzdialenostField, value) != true)) {
                    this.tab6b0ZabrzdnaVzdialenostField = value;
                    this.RaisePropertyChanged("tab6b0ZabrzdnaVzdialenost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData tab6b0Zahlavie {
            get {
                return this.tab6b0ZahlavieField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6b0ZahlavieField, value) != true)) {
                    this.tab6b0ZahlavieField = value;
                    this.RaisePropertyChanged("tab6b0Zahlavie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab6b1Data {
            get {
                return this.tab6b1DataField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6b1DataField, value) != true)) {
                    this.tab6b1DataField = value;
                    this.RaisePropertyChanged("tab6b1Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab6b1UsekTrate {
            get {
                return this.tab6b1UsekTrateField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6b1UsekTrateField, value) != true)) {
                    this.tab6b1UsekTrateField = value;
                    this.RaisePropertyChanged("tab6b1UsekTrate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab6b1ZabrzdnaVzdialenost {
            get {
                return this.tab6b1ZabrzdnaVzdialenostField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6b1ZabrzdnaVzdialenostField, value) != true)) {
                    this.tab6b1ZabrzdnaVzdialenostField = value;
                    this.RaisePropertyChanged("tab6b1ZabrzdnaVzdialenost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData tab6b1Zahlavie {
            get {
                return this.tab6b1ZahlavieField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6b1ZahlavieField, value) != true)) {
                    this.tab6b1ZahlavieField = value;
                    this.RaisePropertyChanged("tab6b1Zahlavie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab6b2Data {
            get {
                return this.tab6b2DataField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6b2DataField, value) != true)) {
                    this.tab6b2DataField = value;
                    this.RaisePropertyChanged("tab6b2Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab6b2UsekTrate {
            get {
                return this.tab6b2UsekTrateField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6b2UsekTrateField, value) != true)) {
                    this.tab6b2UsekTrateField = value;
                    this.RaisePropertyChanged("tab6b2UsekTrate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab6b2ZabrzdnaVzdialenost {
            get {
                return this.tab6b2ZabrzdnaVzdialenostField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6b2ZabrzdnaVzdialenostField, value) != true)) {
                    this.tab6b2ZabrzdnaVzdialenostField = value;
                    this.RaisePropertyChanged("tab6b2ZabrzdnaVzdialenost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData tab6b2Zahlavie {
            get {
                return this.tab6b2ZahlavieField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6b2ZahlavieField, value) != true)) {
                    this.tab6b2ZahlavieField = value;
                    this.RaisePropertyChanged("tab6b2Zahlavie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab6b3Data {
            get {
                return this.tab6b3DataField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6b3DataField, value) != true)) {
                    this.tab6b3DataField = value;
                    this.RaisePropertyChanged("tab6b3Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab6b3UsekTrate {
            get {
                return this.tab6b3UsekTrateField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6b3UsekTrateField, value) != true)) {
                    this.tab6b3UsekTrateField = value;
                    this.RaisePropertyChanged("tab6b3UsekTrate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab6b3ZabrzdnaVzdialenost {
            get {
                return this.tab6b3ZabrzdnaVzdialenostField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6b3ZabrzdnaVzdialenostField, value) != true)) {
                    this.tab6b3ZabrzdnaVzdialenostField = value;
                    this.RaisePropertyChanged("tab6b3ZabrzdnaVzdialenost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData tab6b3Zahlavie {
            get {
                return this.tab6b3ZahlavieField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6b3ZahlavieField, value) != true)) {
                    this.tab6b3ZahlavieField = value;
                    this.RaisePropertyChanged("tab6b3Zahlavie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab6b4Data {
            get {
                return this.tab6b4DataField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6b4DataField, value) != true)) {
                    this.tab6b4DataField = value;
                    this.RaisePropertyChanged("tab6b4Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab6b4UsekTrate {
            get {
                return this.tab6b4UsekTrateField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6b4UsekTrateField, value) != true)) {
                    this.tab6b4UsekTrateField = value;
                    this.RaisePropertyChanged("tab6b4UsekTrate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab6b4ZabrzdnaVzdialenost {
            get {
                return this.tab6b4ZabrzdnaVzdialenostField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6b4ZabrzdnaVzdialenostField, value) != true)) {
                    this.tab6b4ZabrzdnaVzdialenostField = value;
                    this.RaisePropertyChanged("tab6b4ZabrzdnaVzdialenost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData tab6b4Zahlavie {
            get {
                return this.tab6b4ZahlavieField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6b4ZahlavieField, value) != true)) {
                    this.tab6b4ZahlavieField = value;
                    this.RaisePropertyChanged("tab6b4Zahlavie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab6b5Data {
            get {
                return this.tab6b5DataField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6b5DataField, value) != true)) {
                    this.tab6b5DataField = value;
                    this.RaisePropertyChanged("tab6b5Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab6b5UsekTrate {
            get {
                return this.tab6b5UsekTrateField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6b5UsekTrateField, value) != true)) {
                    this.tab6b5UsekTrateField = value;
                    this.RaisePropertyChanged("tab6b5UsekTrate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab6b5ZabrzdnaVzdialenost {
            get {
                return this.tab6b5ZabrzdnaVzdialenostField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6b5ZabrzdnaVzdialenostField, value) != true)) {
                    this.tab6b5ZabrzdnaVzdialenostField = value;
                    this.RaisePropertyChanged("tab6b5ZabrzdnaVzdialenost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData tab6b5Zahlavie {
            get {
                return this.tab6b5ZahlavieField;
            }
            set {
                if ((object.ReferenceEquals(this.tab6b5ZahlavieField, value) != true)) {
                    this.tab6b5ZahlavieField = value;
                    this.RaisePropertyChanged("tab6b5Zahlavie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab7Data {
            get {
                return this.tab7DataField;
            }
            set {
                if ((object.ReferenceEquals(this.tab7DataField, value) != true)) {
                    this.tab7DataField = value;
                    this.RaisePropertyChanged("tab7Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData tab7Zahlavie {
            get {
                return this.tab7ZahlavieField;
            }
            set {
                if ((object.ReferenceEquals(this.tab7ZahlavieField, value) != true)) {
                    this.tab7ZahlavieField = value;
                    this.RaisePropertyChanged("tab7Zahlavie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab8aData {
            get {
                return this.tab8aDataField;
            }
            set {
                if ((object.ReferenceEquals(this.tab8aDataField, value) != true)) {
                    this.tab8aDataField = value;
                    this.RaisePropertyChanged("tab8aData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab8aRekuperaciaData {
            get {
                return this.tab8aRekuperaciaDataField;
            }
            set {
                if ((object.ReferenceEquals(this.tab8aRekuperaciaDataField, value) != true)) {
                    this.tab8aRekuperaciaDataField = value;
                    this.RaisePropertyChanged("tab8aRekuperaciaData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData tab8aRekuperaciaZahlavie {
            get {
                return this.tab8aRekuperaciaZahlavieField;
            }
            set {
                if ((object.ReferenceEquals(this.tab8aRekuperaciaZahlavieField, value) != true)) {
                    this.tab8aRekuperaciaZahlavieField = value;
                    this.RaisePropertyChanged("tab8aRekuperaciaZahlavie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData tab8aZahlavie {
            get {
                return this.tab8aZahlavieField;
            }
            set {
                if ((object.ReferenceEquals(this.tab8aZahlavieField, value) != true)) {
                    this.tab8aZahlavieField = value;
                    this.RaisePropertyChanged("tab8aZahlavie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab8bData {
            get {
                return this.tab8bDataField;
            }
            set {
                if ((object.ReferenceEquals(this.tab8bDataField, value) != true)) {
                    this.tab8bDataField = value;
                    this.RaisePropertyChanged("tab8bData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData tab8bZahlavie {
            get {
                return this.tab8bZahlavieField;
            }
            set {
                if ((object.ReferenceEquals(this.tab8bZahlavieField, value) != true)) {
                    this.tab8bZahlavieField = value;
                    this.RaisePropertyChanged("tab8bZahlavie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData[] tab9Data {
            get {
                return this.tab9DataField;
            }
            set {
                if ((object.ReferenceEquals(this.tab9DataField, value) != true)) {
                    this.tab9DataField = value;
                    this.RaisePropertyChanged("tab9Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KangoMetody.ServiceKango.WSData tab9Zahlavie {
            get {
                return this.tab9ZahlavieField;
            }
            set {
                if ((object.ReferenceEquals(this.tab9ZahlavieField, value) != true)) {
                    this.tab9ZahlavieField = value;
                    this.RaisePropertyChanged("tab9Zahlavie");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceKango.IKmenWS")]
    public interface IKmenWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/login", ReplyAction="http://tempuri.org/IKmenWS/loginResponse")]
        bool login(string loginname, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/login", ReplyAction="http://tempuri.org/IKmenWS/loginResponse")]
        System.Threading.Tasks.Task<bool> loginAsync(string loginname, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/getProjekty", ReplyAction="http://tempuri.org/IKmenWS/getProjektyResponse")]
        KangoMetody.ServiceKango.WSProjekt[] getProjekty();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/getProjekty", ReplyAction="http://tempuri.org/IKmenWS/getProjektyResponse")]
        System.Threading.Tasks.Task<KangoMetody.ServiceKango.WSProjekt[]> getProjektyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/selectProjekt", ReplyAction="http://tempuri.org/IKmenWS/selectProjektResponse")]
        bool selectProjekt(KangoMetody.ServiceKango.WSProjekt projekt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/selectProjekt", ReplyAction="http://tempuri.org/IKmenWS/selectProjektResponse")]
        System.Threading.Tasks.Task<bool> selectProjektAsync(KangoMetody.ServiceKango.WSProjekt projekt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/getEntityInfo", ReplyAction="http://tempuri.org/IKmenWS/getEntityInfoResponse")]
        KangoMetody.ServiceKango.WSEntityInfo[] getEntityInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/getEntityInfo", ReplyAction="http://tempuri.org/IKmenWS/getEntityInfoResponse")]
        System.Threading.Tasks.Task<KangoMetody.ServiceKango.WSEntityInfo[]> getEntityInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/getAllEntityInfo", ReplyAction="http://tempuri.org/IKmenWS/getAllEntityInfoResponse")]
        KangoMetody.ServiceKango.WSEntityInfo[] getAllEntityInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/getAllEntityInfo", ReplyAction="http://tempuri.org/IKmenWS/getAllEntityInfoResponse")]
        System.Threading.Tasks.Task<KangoMetody.ServiceKango.WSEntityInfo[]> getAllEntityInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/getPropertyInfo", ReplyAction="http://tempuri.org/IKmenWS/getPropertyInfoResponse")]
        KangoMetody.ServiceKango.WSPropertyInfo[] getPropertyInfo(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/getPropertyInfo", ReplyAction="http://tempuri.org/IKmenWS/getPropertyInfoResponse")]
        System.Threading.Tasks.Task<KangoMetody.ServiceKango.WSPropertyInfo[]> getPropertyInfoAsync(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/getFidInfo", ReplyAction="http://tempuri.org/IKmenWS/getFidInfoResponse")]
        KangoMetody.ServiceKango.WSPropertyInfo[] getFidInfo(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/getFidInfo", ReplyAction="http://tempuri.org/IKmenWS/getFidInfoResponse")]
        System.Threading.Tasks.Task<KangoMetody.ServiceKango.WSPropertyInfo[]> getFidInfoAsync(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/getAllFidInfo", ReplyAction="http://tempuri.org/IKmenWS/getAllFidInfoResponse")]
        KangoMetody.ServiceKango.WSPropertyInfo[] getAllFidInfo(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/getAllFidInfo", ReplyAction="http://tempuri.org/IKmenWS/getAllFidInfoResponse")]
        System.Threading.Tasks.Task<KangoMetody.ServiceKango.WSPropertyInfo[]> getAllFidInfoAsync(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/getData", ReplyAction="http://tempuri.org/IKmenWS/getDataResponse")]
        KangoMetody.ServiceKango.WSData[] getData(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/getData", ReplyAction="http://tempuri.org/IKmenWS/getDataResponse")]
        System.Threading.Tasks.Task<KangoMetody.ServiceKango.WSData[]> getDataAsync(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/getEntity", ReplyAction="http://tempuri.org/IKmenWS/getEntityResponse")]
        KangoMetody.ServiceKango.WSEntity getEntity(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/getEntity", ReplyAction="http://tempuri.org/IKmenWS/getEntityResponse")]
        System.Threading.Tasks.Task<KangoMetody.ServiceKango.WSEntity> getEntityAsync(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/getWSInfo", ReplyAction="http://tempuri.org/IKmenWS/getWSInfoResponse")]
        KangoMetody.ServiceKango.WSInfo getWSInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/getWSInfo", ReplyAction="http://tempuri.org/IKmenWS/getWSInfoResponse")]
        System.Threading.Tasks.Task<KangoMetody.ServiceKango.WSInfo> getWSInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/logout", ReplyAction="http://tempuri.org/IKmenWS/logoutResponse")]
        void logout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/logout", ReplyAction="http://tempuri.org/IKmenWS/logoutResponse")]
        System.Threading.Tasks.Task logoutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/getTTP", ReplyAction="http://tempuri.org/IKmenWS/getTTPResponse")]
        KangoMetody.ServiceKango.WSDataTTP[] getTTP(int platnost, string ttpcislo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKmenWS/getTTP", ReplyAction="http://tempuri.org/IKmenWS/getTTPResponse")]
        System.Threading.Tasks.Task<KangoMetody.ServiceKango.WSDataTTP[]> getTTPAsync(int platnost, string ttpcislo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKmenWSChannel : KangoMetody.ServiceKango.IKmenWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KmenWSClient : System.ServiceModel.ClientBase<KangoMetody.ServiceKango.IKmenWS>, KangoMetody.ServiceKango.IKmenWS {
        
        public KmenWSClient() {
        }
        
        public KmenWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KmenWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KmenWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KmenWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool login(string loginname, string password) {
            return base.Channel.login(loginname, password);
        }
        
        public System.Threading.Tasks.Task<bool> loginAsync(string loginname, string password) {
            return base.Channel.loginAsync(loginname, password);
        }
        
        public KangoMetody.ServiceKango.WSProjekt[] getProjekty() {
            return base.Channel.getProjekty();
        }
        
        public System.Threading.Tasks.Task<KangoMetody.ServiceKango.WSProjekt[]> getProjektyAsync() {
            return base.Channel.getProjektyAsync();
        }
        
        public bool selectProjekt(KangoMetody.ServiceKango.WSProjekt projekt) {
            return base.Channel.selectProjekt(projekt);
        }
        
        public System.Threading.Tasks.Task<bool> selectProjektAsync(KangoMetody.ServiceKango.WSProjekt projekt) {
            return base.Channel.selectProjektAsync(projekt);
        }
        
        public KangoMetody.ServiceKango.WSEntityInfo[] getEntityInfo() {
            return base.Channel.getEntityInfo();
        }
        
        public System.Threading.Tasks.Task<KangoMetody.ServiceKango.WSEntityInfo[]> getEntityInfoAsync() {
            return base.Channel.getEntityInfoAsync();
        }
        
        public KangoMetody.ServiceKango.WSEntityInfo[] getAllEntityInfo() {
            return base.Channel.getAllEntityInfo();
        }
        
        public System.Threading.Tasks.Task<KangoMetody.ServiceKango.WSEntityInfo[]> getAllEntityInfoAsync() {
            return base.Channel.getAllEntityInfoAsync();
        }
        
        public KangoMetody.ServiceKango.WSPropertyInfo[] getPropertyInfo(int entityID) {
            return base.Channel.getPropertyInfo(entityID);
        }
        
        public System.Threading.Tasks.Task<KangoMetody.ServiceKango.WSPropertyInfo[]> getPropertyInfoAsync(int entityID) {
            return base.Channel.getPropertyInfoAsync(entityID);
        }
        
        public KangoMetody.ServiceKango.WSPropertyInfo[] getFidInfo(int entityID) {
            return base.Channel.getFidInfo(entityID);
        }
        
        public System.Threading.Tasks.Task<KangoMetody.ServiceKango.WSPropertyInfo[]> getFidInfoAsync(int entityID) {
            return base.Channel.getFidInfoAsync(entityID);
        }
        
        public KangoMetody.ServiceKango.WSPropertyInfo[] getAllFidInfo(int entityID) {
            return base.Channel.getAllFidInfo(entityID);
        }
        
        public System.Threading.Tasks.Task<KangoMetody.ServiceKango.WSPropertyInfo[]> getAllFidInfoAsync(int entityID) {
            return base.Channel.getAllFidInfoAsync(entityID);
        }
        
        public KangoMetody.ServiceKango.WSData[] getData(int entityID) {
            return base.Channel.getData(entityID);
        }
        
        public System.Threading.Tasks.Task<KangoMetody.ServiceKango.WSData[]> getDataAsync(int entityID) {
            return base.Channel.getDataAsync(entityID);
        }
        
        public KangoMetody.ServiceKango.WSEntity getEntity(int entityID) {
            return base.Channel.getEntity(entityID);
        }
        
        public System.Threading.Tasks.Task<KangoMetody.ServiceKango.WSEntity> getEntityAsync(int entityID) {
            return base.Channel.getEntityAsync(entityID);
        }
        
        public KangoMetody.ServiceKango.WSInfo getWSInfo() {
            return base.Channel.getWSInfo();
        }
        
        public System.Threading.Tasks.Task<KangoMetody.ServiceKango.WSInfo> getWSInfoAsync() {
            return base.Channel.getWSInfoAsync();
        }
        
        public void logout() {
            base.Channel.logout();
        }
        
        public System.Threading.Tasks.Task logoutAsync() {
            return base.Channel.logoutAsync();
        }
        
        public KangoMetody.ServiceKango.WSDataTTP[] getTTP(int platnost, string ttpcislo) {
            return base.Channel.getTTP(platnost, ttpcislo);
        }
        
        public System.Threading.Tasks.Task<KangoMetody.ServiceKango.WSDataTTP[]> getTTPAsync(int platnost, string ttpcislo) {
            return base.Channel.getTTPAsync(platnost, ttpcislo);
        }
    }
}
